#!/bin/bash
####################################################
git pull
####################################################
# install ubuntu-server 16.04.3
/opt/kc/bin/kc-install init
/opt/kc/bin/kc-install packages
####################################################
#
# create and deploy ssh keys
#
mkdir /root/.ssh
#ssh-keygen -b4096
#cat id_rsa.pub >> authorized_keys
echo "StrictHostKeyChecking=no"     >  /root/.ssh/config
echo "UserKnownHostsFile=/dev/null" >> /root/.ssh/config
scp /root/.ssh/* root@kvm2:/root/.ssh
sed -i "s|#PasswordAuthentication yes|PasswordAuthentication no|" /etc/ssh/sshd_config
/etc/init.d/ssh reload
####################################################
#
# bonding and bridge
#
# https://www.cyberciti.biz/faq/ubuntu-linux-bridging-and-bonding-setup/
# see /etc/network/interfaces
brctl show
cat /proc/net/bonding/bond0 
####################################################
#
# install glusterfs
#
# https://support.rackspace.com/how-to/set-up-a-two-server-glusterfs-array/
# https://github.com/gluster/glusterfs-specs/blob/master/done/GlusterFS%203.5/Virt%20store%20usecase.md
# http://www.admin-magazine.com/Articles/Build-storage-pools-with-GlusterFS/(offset)/3

# resolve qemu port conflict:
vi /etc/glusterfs/glusterd.vol
 option base-port 50152
echo "10.10.10.1      gfs1" >> /etc/hosts
echo "10.10.10.2      gfs2" >> /etc/hosts

lsblk
vgcreate data  /dev/sdb
#lvcreate -n tsp0 -L 1T data
lvcreate -n tsp0 -l100%FREE data
mkfs.ext4 /dev/data/tsp0
mkdir -p /srv/.bricks 
echo "/dev/data/tsp0 /srv/.bricks ext4 defaults 0 1" >> /etc/fstab 
mount /srv/.bricks
gluster peer probe gfs1
gluster peer probe gfs2

GLUSTER_VOL="cust"
gluster volume create ${GLUSTER_VOL} replica 2 gfs1://srv/.bricks/${GLUSTER_VOL} gfs2://srv/.bricks/${GLUSTER_VOL}
gluster volume start  ${GLUSTER_VOL}
gluster volume info

echo "localhost:${GLUSTER_VOL} /tsp0  glusterfs log-file=/var/log/mirror.vol,defaults,_netdev,noauto,x-systemd.automount 0 0" >> /etc/fstab
mount -a

####################################################
#
# download cd images for testing
#
kc-getiso alpine
kc-getiso ubuntu

#####################################################
#
# Hints
#
* nach migrate ist Autostart der VM nicht mehr aktiv
* migrate zwischen verschiedenen Host-CPUs: guest-cpu wie Ziel cpu einstellen
* nach Aktivieren eines snapshot muss vor einem migrate erst ein Restart der vm durchgeführt werden.

